### ISSUE TITLE
SAM does not support Steam Families Beta

### ISSUE THREAD

**Issue by lovexuan** [syntax-tm/SteamAchievementManager#25]
I can load game list but cannot load achievements when I use Steam Families Beta.

After I switch back to normal build, I can load them.

I guess steam change the arguments on Families Beta.

```
SteamStatsManager [6] - An error occurred handling stats retrieval. Specified argument was out of the range of valid values. (Parameter 'stat')
System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values. (Parameter 'stat')
   at SAM.Stats.SteamStatisticFactory.CreateStat(Client client, StatInfoBase stat) in D:\a\SteamAchievementManager\SteamAchievementManager\src\SAM\Stats\Factories\SteamStatisticFactory.cs:line 57
   at SAM.Stats.SteamStatsManager.GetStatistics() in D:\a\SteamAchievementManager\SteamAchievementManager\src\SAM\Stats\SteamStatsManager.cs:line 279
   at SAM.Stats.SteamStatsManager.OnUserStatsReceived(UserStatsResponse param) in D:\a\SteamAchievementManager\SteamAchievementManager\src\SAM\Stats\SteamStatsManager.cs:line 144
SAM (673610) 2024-07-17 21:04:04,897 ERROR SteamStatsManager [6] - An error occurred handling stats retrieval. Specified argument was out of the range of valid values. (Parameter 'stat')
System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values. (Parameter 'stat')
   at SAM.Stats.SteamStatisticFactory.CreateStat(Client client, StatInfoBase stat) in D:\a\SteamAchievementManager\SteamAchievementManager\src\SAM\Stats\Factories\SteamStatisticFactory.cs:line 57
   at SAM.Stats.SteamStatsManager.GetStatistics() in D:\a\SteamAchievementManager\SteamAchievementManager\src\SAM\Stats\SteamStatsManager.cs:line 279
   at SAM.Stats.SteamStatsManager.OnUserStatsReceived(UserStatsResponse param) in D:\a\SteamAchievementManager\SteamAchievementManager\src\SAM\Stats\SteamStatsManager.cs:line 144
SAM (270880) 2024-07-17 21:05:33,701 ERROR SteamStatsManager [6] - An error occurred handling stats retrieval. Specified argument was out of the range of valid values. (Parameter 'stat')
System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values. (Parameter 'stat')
   at SAM.Stats.SteamStatisticFactory.CreateStat(Client client, StatInfoBase stat) in D:\a\SteamAchievementManager\SteamAchievementManager\src\SAM\Stats\Factories\SteamStatisticFactory.cs:line 57
   at SAM.Stats.SteamStatsManager.GetStatistics() in D:\a\SteamAchievementManager\SteamAchievementManager\src\SAM\Stats\SteamStatsManager.cs:line 279
   at SAM.Stats.SteamStatsManager.OnUserStatsReceived(UserStatsResponse param) in D:\a\SteamAchievementManager\SteamAchievementManager\src\SAM\Stats\SteamStatsManager.cs:line 144
SAM (289070) 2024-07-17 21:09:49,523 ERROR SteamStatsManager [6] - An error occurred handling stats retrieval. Specified argument was out of the range of valid values. (Parameter 'stat')
System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values. (Parameter 'stat')
   at SAM.Stats.SteamStatisticFactory.CreateStat(Client client, StatInfoBase stat) in D:\a\SteamAchievementManager\SteamAchievementManager\src\SAM\Stats\Factories\SteamStatisticFactory.cs:line 57
   at SAM.Stats.SteamStatsManager.GetStatistics() in D:\a\SteamAchievementManager\SteamAchievementManager\src\SAM\Stats\SteamStatsManager.cs:line 279
   at SAM.Stats.SteamStatsManager.OnUserStatsReceived(UserStatsResponse param) in D:\a\SteamAchievementManager\SteamAchievementManager\src\SAM\Stats\SteamStatsManager.cs:line 144
```

**Comment by syntax-tm** [comment]
Which version of the app are you using?

**Comment by syntax-tm** [comment]
I use the Steam Families Beta so that's definitely not the issue (assuming you are on the latest). Is this a game that you own or is it owned by a family member?

**Comment by lovexuan** [comment]
> I use the Steam Families Beta so that's definitely not the issue (assuming you are on the latest). Is this a game that you own or is it owned by a family member?

All those games are owned by me.

I just switch to Steam Families Beta so it should be the latest.

And I use the latest SAM v0.6.0 release version.

**Comment by syntax-tm** [comment]
Try the latest pre-release. I just left my Steam Family so I can't easily join a new one (for a year or so), but I was able to use it with that update fine. Still on that update without being in a family and no issues. Let me know if it's still an issue on the latest pre-release.

[v0.7.0-beta](https://github.com/syntax-tm/SteamAchievementManager/releases/tag/v0.7.0-beta)

**Comment by lovexuan** [comment]
> Try the latest pre-release. I just left my Steam Family so I can't easily join a new one (for a year or so), but I was able to use it with that update fine. Still on that update without being in a family and no issues. Let me know if it's still an issue on the latest pre-release.
> 
> [v0.7.0-beta](https://github.com/syntax-tm/SteamAchievementManager/releases/tag/v0.7.0-beta)

![QQ_1721910609426](https://github.com/user-attachments/assets/259c5b82-1fe6-4bc3-b855-0fe59f66643a)
Still there.

```
2024-07-25 20:29:01,752 ERROR SteamStatsManager [5] - An error occurred handling stats retrieval. Specified argument was out of the range of valid values. (Parameter 'stat')
System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values. (Parameter 'stat')
   at SAM.Stats.SteamStatisticFactory.CreateStat(Client client, StatInfoBase stat) in D:\a\SteamAchievementManager\SteamAchievementManager\src\SAM\Stats\Factories\SteamStatisticFactory.cs:line 57
   at SAM.Stats.SteamStatsManager.GetStatistics() in D:\a\SteamAchievementManager\SteamAchievementManager\src\SAM\Stats\SteamStatsManager.cs:line 280
   at SAM.Stats.SteamStatsManager.OnUserStatsReceived(UserStatsResponse param) in D:\a\SteamAchievementManager\SteamAchievementManager\src\SAM\Stats\SteamStatsManager.cs:line 145
```

**Comment by syntax-tm** [comment]
Is it only that game? It's $4.99 right now I don't want it but might buy it if it's only that app having issues.

**Comment by lovexuan** [comment]
> Is it only that game? It's $4.99 right now I don't want it but might buy it if it's only that app having issues.

Not only, but yes, I check all of my games, and some of them can be loaded(such as Euro Truck Simulator 2, Cities Skylines 2, Airport CEO, etc...), some of them cannot(American Truck Simulator, Dyson Sphere Program, Factory Town, Forager, etc...).

But if one game cannot be loaded, it will never be loaded though I tries over ten times. So I think it's a stable bug related by games.

**Comment by lovexuan** [comment]
> > Is it only that game? It's $4.99 right now I don't want it but might buy it if it's only that app having issues.
> 
> Not only, but yes, I check all of my games, and some of them can be loaded(such as Euro Truck Simulator 2, Cities Skylines 2, Airport CEO, etc...), some of them cannot(American Truck Simulator, Dyson Sphere Program, Factory Town, Forager, etc...).
> 
> But if one game cannot be loaded, it will never be loaded though I tries over ten times. So I think it's a stable bug related by games.

Seems like Steam Families Beta has an A/B test policy for games. So I'm not sure you will hit the same policy to me. Maybe you can try all your games to see if anyone have the same issue.

**Comment by maconho** [comment]
In my case SAM doesn't loaded any achievements from family games since July 16th beta Steam update. So I try install some game from family, open the game and then open the manager in SAM while the game was open and it work for that specific game from family, but stop to load the achievements from my own games. Then I launch one of my own game from Steam and open de manager for that game in SAM and it worked for that game. Currently in my own games SAM load achievements in some games and others not. Same thing for family games, some loads, some don't. Seens Valve change something in how the API handle with player id on requests in the beta client for games in family share.

**Comment by syntax-tm** [comment]
Yeah I'll dump `steamclient.dll` and see what changed. Also check and see if there's a new Steamworks SDK or something that has all the interface versions and stuff.

**Comment by maconho** [comment]
Some user on Gibbed original branch comes with the solution "Temporary fix: open the game page (don't need to launch the game) in your Steam Library before opening it with SAM.". Can confirm that works perfectly this way, for my own games and also for family games. Somehow SAM don't recognize the parameters anymore on Steam Beta if the game page isn't open.

**Comment by Mandydeth** [comment]
> Some user on Gibbed original branch comes with the solution "Temporary fix: open the game page (don't need to launch the game) in your Steam Library before opening it with SAM.". Can confirm that works perfectly this way, for my own games and also for family games. Somehow SAM don't recognize the parameters anymore on Steam Beta if the game page isn't open.

Very useful. Can confirm I was having the same issue, and this solution resolves it for the time being.

**Comment by maconho** [comment]
> Yeah I'll dump `steamclient.dll` and see what changed. Also check and see if there's a new Steamworks SDK or something that has all the interface versions and stuff.

Gibbed found the problem and post a correction on original branch. Please check the discution on this link:

https://github.com/gibbed/SteamAchievementManager/issues/413

And the fix update in this link:

https://github.com/gibbed/SteamAchievementManager/commit/b3a66df0d1a870e1646a259698a670f6884fa7c9

**Comment by maconho** [comment]
Also. The the Steam Families client is now the main one, this is not a problem only for beta version.

**Comment by maconho** [comment]
It seems like this problem doesn't happen anymore. Looks like that some Steam update auto solve the question. Now any game show the achievements when click on Manage button, even if the game isn't selected on Steam Library.

**Comment by syntax-tm** [comment]
Yeah I actually tested this again the other day and didn't experience any issues unlocking an achievement in a Family member's game. Tested ones we both own, only they own, and then ones only I own and can't replicate this anymore. For now I'm going to close this but if anything comes up please open a new ticket. Appreciate your following up too.
